name: scrape

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  download_and_unzip_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11


    - name: install poetry
      uses: snok/install-poetry@v1

    - name: install dependencies
      run: poetry install --no-interaction --no-root --without dev

    - name: Download data
      run: |
        curl -L -o openipf-latest.zip "https://openpowerlifting.gitlab.io/opl-csv/files/openipf-latest.zip"


    - name: Load data
      run: poetry run python steps/01_load_data.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Download, unzip, and convert OpenIPF data to Parquet"
        git push

